import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";
import ReduxProvider from "@/redux/ReduxProvider/ReduxProvider";

import { saira } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "BIKE-BOOKING",
  description: "Generated by create next app",
  openGraph: {
    images: "/favicon.ico",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className={saira.className}>
        <ReduxProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
